version: '2'
services:
    reservemanagement-app:
        image: reservemanagement
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://reservemanagement-mysql:3306/reservemanagement?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    reservemanagement-mysql:
        extends:
            file: mysql.yml
            service: reservemanagement-mysql
